### ISSUE TITLE
Duty second panel all black

### ISSUE THREAD

**Issue by KiwiMonkeyUSA** [Sevii77/frost_ui#14]
Hi. I have Pen+Aetherment/FrostUI installed. I have a collection in Pen called UI and under collections, Interface is set to use my UI collection.  Under mods tab in Pen, Frost UI shows up in left and i have it enabled w/ a priority of 1. In the aetherment panel, I have frostUI installed and on preset set to "Material UI" and all the colors/options are default. With that set, everything looks great, except the duty finder "U". The left side is materialUI, but the right side is completely black and unable to read anything. Any suggestions?

Also, side questions...browser tab in /aetherment, what's the difference between frostui and materialui install? and how do we access the presets that are exampled in the readme/instructions?

Thanks.

![image](https://github.com/user-attachments/assets/ea46b0e0-2c3c-452d-bb2c-5b3202aa458e)

**Comment by Sevii77** [comment]
The black panel is by design, the text is supposed to be white. Try reenabling the plugin, there's currently a bug where it sometimes doesn't properly load text colors.

Material UI in the browser is the original maintained by valeriae and can be found [here](https://github.com/ValeriaeWasTaken/Material-UI-Reborn), while the preset in Frost UI is still Frost but with settings to imitate Material UI.

As for the presets on the README, the default ones are build in and the others can be found in the #frost-preset-sharing channel on the discord, an invite link for which can be found on the README aswell.
