### ISSUE TITLE
dont understand how to make it works

### ISSUE THREAD

**Issue by mattiaperry95** [Sevii77/frost_ui#3]
as title. dont understand how to make it works. i added the reposit and have openend the menu, installed the frost ui but nothing changes even after clicking apply. would be good to have some more detailed instruction

**Comment by ShichiIzanagi** [comment]
You need Penumbra installed first and foremost - if you did that and downloaded the mod via Aetherment it will be in your penumbra mod window.

You need to first make a new collection for your UI Stuff 
![grafik](https://github.com/user-attachments/assets/b5d55fec-2c70-483f-a443-5f04bec03689)
Like in this pic (its just hiding my names dont worry about the numbers)
Name it "UI Stuff" or what ever. Click on where it says "Interface" and tell it to use your new UI Collection.
Go to your Mod window and enable the Mod only in that collection 
![grafik](https://github.com/user-attachments/assets/aa8248a0-a6b1-4057-a9d4-1f6e462267b9)
There is a dropdown menu in the top right.

You also need to make sure you have Dark Mode in the FF Theme active and 4K UI Resolution in System Config > Graphic Options 
![grafik](https://github.com/user-attachments/assets/cb243e17-385b-4dac-9e3e-6f4aaeba2cfc)


If you need more help please join the discord and I can help you better.

**Comment by mattiaperry95** [comment]
thnaks! another question, for the material ui instead, is the same? bc i saw that in Aetherment there is a drop down that lets u select frost or material ui

**Comment by Rellawing** [comment]
It's just a very circuitous way to install a mod versus the previous ease. Honestly, it's not that bad, except for having to do x thing to use Penumbra currently, and then use Aetherment to download... and Penumbra to activate said mod, and then Aetherment again to somewhat customize Frost UI.

**Comment by ShichiIzanagi** [comment]
> It's just a very circuitous way to install a mod versus the previous ease. Honestly, it's not that bad, except for having to do x thing to use Penumbra currently, and then use Aetherment to download... and Penumbra to activate said mod, and then Aetherment again to somewhat customize Frost UI.

Its exactly the same way as before with the Material UI Plugin. Nothing has changed in that regard.

**Comment by Rellawing** [comment]
> Its exactly the same way as before with the Material UI Plugin. Nothing has changed in that regard.

It's nothing like how I installed Material UI in the past. Your experience varies from mine.

I got Material UI off Github and imported manually into Penumbra more often. Eventually, I installed the Material UI Accent plugin/repo which came with an auto update function for Material UI, which was very handy! Quite possibly Aetherment will keep the theme updated regularly on its own now, but only experience will show that (or I'm told it will or not).

That's what I mean by it being simpler than now. You either installed it after a brisk download off Github or a modding site like Nexus, with an option of using the FFXIV Textools program to not be deprived of a gorgeously customized UI every time the plugins have to be updated for the patches... The first time I ever used Aetherment was yesterday.

**Comment by ShichiIzanagi** [comment]
> > Its exactly the same way as before with the Material UI Plugin. Nothing has changed in that regard.
> 
> It's nothing like how I installed Material UI in the past. Your experience varies from mine.
> 
> I got Material UI off Github and imported manually into Penumbra more often. Eventually, I installed the Material UI Accent plugin/repo which came with an auto update function for Material UI, which was very handy! Quite possibly Aetherment will keep the theme updated regularly on its own now, but only experience will show that (or I'm told it will or not).
> 
> That's what I mean by it being simpler than now. You either installed it after a brisk download off Github or a modding site like Nexus, with an option of using the FFXIV Textools program to not be deprived of a gorgeously customized UI every time the plugins have to be updated for the patches... The first time I ever used Aetherment was yesterday.

It already has an auto update for the theme. Installing only the ttmp into penumbra offered no customization and you had to optionally install other files to make it custom. Both the MUI/Aetherment plugin offer customization that you cant do with Textools of installing manually. Installing manually never changed and the plugin way didnt change either, its essentially still the same in the end. Just people are confused since its new-ish. Well and Frost still being very early beta it doesnt have all the options yet, but soon.

**Comment by Rellawing** [comment]
> It already has an auto update for the theme.

Sevii's Material UI Accent plugin certainly did for a time, as I said. However, Aetherment is relatively new, an entirely new plugin to me.

> Installing only the ttmp into penumbra offered no customization and you had to optionally install other files to make it custom.

This very author published a plugin that modified and updated MaterialUI to the latest version. It seems that's a thing that you never discovered. It can be found here: https://github.com/Sevii77/ffxiv_materialui_accent

I'm not sure if you're trying to deny that my method of updating MaterialUI ever existed or are talking about some tangent subject.

> Installing manually never changed and the plugin way didnt change either, its essentially still the same in the end.

It was customization such as offered with FrostUI today. One of my favorite customization through Sevii's plugin disabled the macro gear icons, making them look more like real abilities, though I had to remember which were macros and not. This line kind of indicates that you totally weren't aware of his plugin.

> Both the MUI/Aetherment plugin offer customization that you cant do with Textools of installing manually.

At the moment, it doesn't yet do much for me. It exists entirely for the sake of FrostUI. Aetherment offers only the customization and updating functions that MaterialUI Accent did. Developers might find its other functions useful, but for laymen, it's just an updater and modifier.

> Just people are confused since its new-ish. 

Not just because it's newish.  They're confused by the process. At the moment, I had to figure it out myself with a little hint that Testing had to be enabled to start with so that Penumbra could be updated and used. Only then would Aetherment work. It had nothing to hook to. Then I had to go back to Penumbra and enable the mod there. After that was over, I found that I wasn't done with the process. A restart would have meant FrostUI activating, but there was also activating the mod in Aetherment, which offered the additional customization and updating services.

If the plugin's page gave a step by step like this, it would be a bit clearer from the ge go, less of a mystery.

> Well and Frost still being very early beta it doesnt have all the options yet, but soon.

Very true that. It's beta, but I find the UI to be beautiful and satisfies my aesthetics more than even MaterialUI could. I'm very happy with this custom UI. I'd say that while FrostUI may continue to see updates and advancements, it'll be Aetherment and the posting of all the steps involved that will evolve most.

If Aetherment was made part of the Penumbra plugin, things would be somewhat simplified. IE: a system that autoupdated textures and such, but as I've found as well, there's yet another program that does just that: Heliosphere. Quick installations, updates right to Penumbra. The modding scene is becoming more powerful and far more interesting as the years pass! The developers astonish me with their creativity and dedication.

It's such a shame that some devs quit like any player that gets burnt out on the game and leave their legacy behind, but thankfully since Sevii had long since been studying and modifying MaterialUI, it was only natural that he would be the inheritor. Seeing that FrostUI exists, though it took some serious searching to find it, filled my heart with joy.

The vanilla ui options are far inferior in my opinion.

**Comment by ShichiIzanagi** [comment]
> This very author published a plugin that modified and updated MaterialUI to the latest version. It seems that's a thing that you never discovered. It can be found here: https://github.com/Sevii77/ffxiv_materialui_accent

> I'm not sure if you're trying to deny that my method of updating MaterialUI ever existed or are talking about some tangent subject.

No you just completely misunderstood me, im not bringing up the MUI plugin anymore because its deprecated I was merely stating that Aetherment offers the same thing now. Again, Aetherment is essentially the same thing, just the successor of MUI and its own plugin/mod now. 

> At the moment, it doesn't yet do much for me. It exists entirely for the sake of FrostUI. Aetherment offers only the customization and updating functions that MaterialUI Accent did. Developers might find its other functions useful, but for laymen, it's just an updater and modifier.

Which the Material UI plugin was aswell, it was just a downloader and modifier so I fail to see the problem.
People are already sharing their creations on the discord and installing optional mods shared in the mod channel to use them alongside.

> Not just because it's newish. They're confused by the process. At the moment, I had to figure it out myself with a little hint that Testing had to be enabled to start with so that Penumbra could be updated and used. Only then would Aetherment work. It had nothing to hook to. Then I had to go back to Penumbra and enable the mod there. After that was over, I found that I wasn't done with the process. A restart would have meant FrostUI activating, but there was also activating the mod in Aetherment, which offered the additional customization and updating services.

> If the plugin's page gave a step by step like this, it would be a bit clearer from the ge go, less of a mystery.

Nothing changed from how the process worked when the MUI Plugin was around, entirely nothing. And theres a guide on the discord aswell, which should be the go to place for questions and issues. Offering support and help on github is not really feasible.

> Very true that. It's beta, but I find the UI to be beautiful and satisfies my aesthetics more than even MaterialUI could. I'm very happy with this custom UI. I'd say that while FrostUI may continue to see updates and advancements, it'll be Aetherment and the posting of all the steps involved that will evolve most.

> If Aetherment was made part of the Penumbra plugin, things would be somewhat simplified. IE: a system that autoupdated textures and such, but as I've found as well, there's yet another program that does just that: Heliosphere. Quick installations, updates right to Penumbra. The modding scene is becoming more powerful and far more interesting as the years pass! The developers astonish me with their creativity and dedication.

> It's such a shame that some devs quit like any player that gets burnt out on the game and leave their legacy behind, but thankfully since Sevii had long since been studying and modifying MaterialUI, it was only natural that he would be the inheritor. Seeing that FrostUI exists, though it took some serious searching to find it, filled my heart with joy.

> The vanilla ui options are far inferior in my opinion.

It cant be part of Penumbra thats not how the plugins work. Aetherment is like I said above just a downloader. If you were to install it manually you could not get the level of customization you have with the plugin, you'd have to install 100 different mods to get the same effect, same as when you would install it with textools, you lose a lot of the custom options.
Heliosphere is something entirely different since it works through a mod distribution website and runs on its own server.

Again, aetherment downloads also straight into penumbra and also auto updates when ever Sevii pushes an update. Its essentially the same just one is only made for one mod, the other is a much more complex tool alongside a website which wont function without it.

**Comment by Rellawing** [comment]
> Nothing changed from how the process worked when the MUI Plugin was around, entirely nothing. And theres a guide on the discord aswell, which should be the go to place for questions and issues. Offering support and help on github is not really feasible.

There's one hole in your arguments here. Other plugins give instructions on how to get started. Not feasible? One of my eyebrows is raised sky high. Guess which one.

> It cant be part of Penumbra thats not how the plugins work.

Through collaboration between developers, it can. But that's a possibility, not a current reality, if ever.

> Aetherment is like I said above just a downloader.

Goodie! Another hole! It's also for configuring Frost UI.

> aetherment downloads also straight into penumbra and also auto updates when ever Sevii pushes an update.

This is called a dependency. That aside, I'd say that the biggest gap in the process is Penumbra being not entirely transparent about how to get it working right now, though they have a Discord with friendly people and mods that help to guide users to the right place.

**Comment by ShichiIzanagi** [comment]
> There's one hole in your arguments here. Other plugins give instructions on how to get started. Not feasible? One of my eyebrows is raised sky high. Guess which one.

Again, you didnt read what I wrote. Theres a step by step guide on the discord. Github will follow eventually but most people are generally on the discord for support/help. Thats on you.

> Through collaboration between developers, it can. But that's a possibility, not a current reality, if ever.

Again not how it works. Penumbra is already "working" with many different plugins, but they can never be intertwined like that or made part of Penumbra, thats not how this works.

> Goodie! Another hole! It's also for configuring Frost UI.

Again you didnt read, I also mentioned that Aetherment is, just like Material UI Plugin a Downloader and Modifier. Which in turn you cant have that kind of customization if you choose not to use the plugin version.

> This is called a dependency. That aside, I'd say that the biggest gap in the process is Penumbra being not entirely transparent about how to get it working right now, though they have a Discord with friendly people and mods that help to guide users to the right place.

https://reniguide.carrd.co/#installpenumbrafull <- this is a very in depth guide on how to get penumbra started, which is even linked on the github. And yes, many plugins depend on penumbra, I think thats pretty obvious.

**Comment by Rellawing** [comment]
> Again, you didnt read what I wrote. Theres a step by step guide on the discord. Github will follow eventually but most people are generally on the discord for support/help. Thats on you.

Nothing's on me. Your toxic bull got nothing on me, because I figured out the riddle days ago. What are you even going on about? What a pest.

> Again not how it works. Penumbra is already "working" with many different plugins, but they can never be intertwined like that or made part of Penumbra, thats not how this works.

Again, many things can happen with collaboration. Or not.

> Again you didnt read, I also mentioned that Aetherment is, just like Material UI Plugin a Downloader and Modifier. Which in turn you cant have that kind of customization if you choose not to use the plugin version.

You didn't mention it being a modifier in your post. I did. You're just taking credit for my talking points. How clever of you.

> https://reniguide.carrd.co/#installpenumbrafull <- this is a very in depth guide on how to get penumbra started, which is even linked on the github. And yes, many plugins depend on penumbra, I think thats pretty obvious.

Good! Let's end this conversation by making this url very visible by posting it a few times so that when people read this amusing conversation, they'll get something good out of it. 

https://reniguide.carrd.co/#installpenumbrafull

Now be so good as to keep yourself out of my hair you swamp thing.

**Comment by ShichiIzanagi** [comment]
> You didn't mention it being a modifier in your post. I did. You're just taking credit for my talking points. How clever of you.

I did, yet again you decided to ignore said points. Legit agreeing with you even with my points.

"Both the MUI/Aetherment plugin offer customization"
"Which the Material UI plugin was aswell, it was just a downloader and modifier (in response to Aetherment)"



>Nothing's on me. Your toxic bull got nothing on me, because I figured out the riddle days ago. What are you even going on about? What a pest.

Point stands, you are deliberatly not reading all im writing, calling me toxic now when I was talking normally here. Good on you.

> Again, many things can happen with collaboration. Or not.

You still fail to grasp how this works despite explaining it to you many times. They already ARE collaborating.

> Good! Let's end this conversation by making this url very visible by posting it a few times so that when people read this amusing conversation, they'll get something good out of it.

https://reniguide.carrd.co/#installpenumbrafull

Now be so good as to keep yourself out of my hair you swamp thing.

By all means, continue being toxic yourself throwing around names already then when all im doing is offer you help and solutions to the issues you seem to have and try to explain. Not my problem if you fail to see the guides and decide to only read parts of what im writing.Good luck on your endeavour.
