### ISSUE TITLE
Enabled but not working.

### ISSUE THREAD

**Issue by Petra105** [Sevii77/frost_ui#8]
looking into the mod none of the files have redirections.

https://i.gyazo.com/ca6035b60c047f0841c2e412d772d419.png

**Comment by ShichiIzanagi** [comment]
The mod is fine, that only says you didnt set it up properly.

**Comment by Sevii77** [comment]
That's by design. Aetherment creates a SingleFile option that it sets on a per collection basis. This way you can have different settings for each collection (has no use for ui mods tho). Be sure to enable the mod in the correct collection and click 'apply' in Aetherment.
![image](https://github.com/user-attachments/assets/6baecee5-9884-474a-95fa-dc45aa1f89a6)
